[versions]
agp = "8.13.2"
kotlin = "1.8.22"
purchases = "9.21.0"
androidxCore = "1.10.1"

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }

[libraries]
androidx-core = { module = "androidx.core:core-ktx", version.ref = "androidxCore" }

lifecycle-runtime-ktx = "androidx.lifecycle:lifecycle-runtime-ktx:2.6.1"
activity-compose = "androidx.activity:activity-compose:1.3.1"
compose-bom = "androidx.compose:compose-bom:2023.05.01"
compose-ui = { module = "androidx.compose.ui:ui" }
compose-ui-graphics = { module = "androidx.compose.ui:ui-graphics" }
compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
compose-material3 = { module = "androidx.compose.material3:material3" }
compose-material = { module = "androidx.compose.material:material" }
navigation-compose = "androidx.navigation:navigation-compose:2.5.3"
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
compose-ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest" }

revenuecat = { module = "com.revenuecat.purchases:purchases-custom-entitlement-computation", version.ref = "purchases" }
