naming:
  FunctionNaming:
    active: true
    functionPattern: '[a-zA-Z][a-zA-Z0-9]*'
    ignoreAnnotated: [ 'Composable' ]
formatting:
  TrailingCommaOnCallSite:
    active: true
    autoCorrect: true
    useTrailingCommaOnCallSite: true
  TrailingCommaOnDeclarationSite:
    active: true
    autoCorrect: true
    useTrailingCommaOnDeclarationSite: true
style:
  UnusedPrivateMember:
    active: true
    ignoreAnnotated: [ 'Preview' ]
